# GitHub Actions for STKAudioKit: includes builds, tests and releases
name: CI

on: [push, pull_request]
env:
  XCODE_VER: latest-stable

jobs:
  test:
    strategy:
      matrix:
        xcode_version: ['12.4']
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - name: Check out STKAudioKit
        uses: actions/checkout@v2
      - name: Build STKAudioKit
        run: |
          set -euo pipefail
          xcodebuild -scheme STKAudioKit -enableAddressSanitizer YES clean build | xcpretty
      - name: Run Tests (ASAN)
        run: |
          set -euo pipefail
          xcodebuild -scheme STKAudioKit -enableAddressSanitizer YES test | xcpretty

  # Generate Wiki docs on release
  docs:
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out STKAudioKit
        uses: actions/checkout@v2
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: "Sources"
          module-name: STKAudioKit
          output: "Documentation"
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "Documentation"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

